### ISSUE TITLE
field 'day' missing in date table

### ISSUE THREAD

**Issue by snelling-a** [pysan3/neorg-templates#3]
Hey, 👋
new to Neorg and I really like what you've done with templates. however, I can't seem to get it working. either in my own config or using yous (`NVIM_APPNAME=pysan3 nim`)

here is the error:

```lua
   Error  Error executing Lua callback: ...ua/neorg/modules/external/templates/default_snippets.lua:50: field 'day' missing in date table
stack traceback:
	[C]: in function 'time'
	...ua/neorg/modules/external/templates/default_snippets.lua:50: in function 'parse_date'
	...andrewsnelling/.config/pys/lua/norg-config/templates.lua:42: in function <...andrewsnelling/.config/pys/lua/norg-config/templates.lua:41>
	...lua/neorg/modules/external/templates/snippet_handler.lua:61: in function 'build_keywords'
	...lua/neorg/modules/external/templates/snippet_handler.lua:98: in function 'create_snippet'
	...lua/neorg/modules/external/templates/snippet_handler.lua:116: in function 'add_snippet_to_luasnip'
	...lua/neorg/modules/external/templates/snippet_handler.lua:152: in function 'on_event'
	...nelling/.local/share/pys/lazy/neorg/lua/neorg/events.lua:153: in function 'broadcast_event'
	...ys/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:289: in function <...ys/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:196>
```
any help would be much appreciated

**Comment by pysan3** [comment]
In my config, the keyword TITLE_YESTERDAY parses the filename and turns it into a date format. 

It requires the filename to be exactly in `2023-06-02.norg` format and then it can calculate _yesterday_ (2023-06-01). So if the file name is not in this specific format, this will fail. (So requires `strategy = "flat"` in ["core.journal" config](https://github.com/nvim-neorg/neorg/wiki/Journal#the-strategy-to-use-to-create-directoriesmay-be-flat-2022-03-02norg-nested-20220302norga-lua-string-with-the-format-given-to-osdate-or-a-lua-functionthat-returns-a-lua-string-with-the-same-format). 

This key is [defined](https://github.com/pysan3/dotfiles/blob/f1bf925b98e473338a2765e323c6f78a4d55ece1/nvim/lua/norg-config/templates.lua#L38) in my own config and was not really meant to be used by everyone. 

So the traceback you pasted should be caused by invoking journal template on file with wrong file name. 

You could either change TITLE_YESTERDAY to YESTERDAY (this key is in the defaults and calculates based on `os.time()`, or fix the file name. Same for TITLE_TOMORROW. 

And the error you previously got with _your_ config might have been different from what you posted. If so, could you post the traceback you got with your config as well as the template you used?

**Comment by snelling-a** [comment]
just to clarify, the error above is using `NVIM_APPNAME` with your config. i get the same error with my config:

```lua
   Error  Error executing Lua callback: ...ua/neorg/modules/external/templates/default_snippets.lua:50: field 'day' missing in date table
stack traceback:
	[C]: in function 'time'
	...ua/neorg/modules/external/templates/default_snippets.lua:50: in function 'parse_date'
	/Users/andrewsnelling/.config/nvim/lua/norg/templates.lua:17: in function </Users/andrewsnelling/.config/nvim/lua/norg/templates.lua:17>  <- HERE
	...lua/neorg/modules/external/templates/snippet_handler.lua:61: in function 'build_keywords'
	...lua/neorg/modules/external/templates/snippet_handler.lua:98: in function 'create_snippet'
	...lua/neorg/modules/external/templates/snippet_handler.lua:116: in function 'add_snippet_to_luasnip'
	...lua/neorg/modules/external/templates/snippet_handler.lua:152: in function 'on_event'
	...elling/.local/share/nvim/lazy/neorg/lua/neorg/events.lua:153: in function 'broadcast_event'
	...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:289: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:196>
```
i've marked the line that is different
you're right in that it does seem to be connected to the title `strategy`, however if i change it to `flat` in my config i get a different error:
```lua 
   Error  Error executing vim.schedule lua callback: vim/_editor.lua:0: nvim_exec2(): Vim:Error executing Lua callback: vim/_editor.lua:0: nvim_exec2()..nvim_exec2() called at nvim_exec2():0: Vim(normal):E21: Cannot make changes, 'modifiable' is off
stack traceback:
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...emplates/lua/neorg/modules/external/templates/module.lua:107: in function 'on_event'
	...elling/.local/share/nvim/lazy/neorg/lua/neorg/events.lua:153: in function 'broadcast_event'
	...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:289: in function <...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:196>
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...im/lazy/neorg/lua/neorg/modules/core/neorgcmd/module.lua:417: in function 'on_choice'
	...are/nvim/lazy/dressing.nvim/lua/dressing/select/init.lua:78: in function ''
```
i hav even tried inputting the dates not from the filename and get a different error:

same error if i pass the dates like this:
<details>
```
lua
local now = tonumber(os.time())
local one_day = 86400.0
local time_yesterday = now - one_day
local time_tomorrow = now + one_day

local y = os.date("*t", time_yesterday)
local t = os.date("*t", time_tomorrow)

local yesterday = string.format("%4d-%02d-%02d", y.year, y.month, y.day)
local tomorrow = string.format("%4d-%02d-%02d", t.year, t.month, t.day)

print(yesterday)
M.keywords = {
	TITLE_YESTERDAY = yesterday,
	TITLE_TOMORROW = tomorrow,
}

return M
```
</details>

**Comment by pysan3** [comment]
Thanks for the details. 

Your error seems to be saying that the buffer you invoked the command is not modifiable, hence cannot load the template in that buffer. Try running the command while on the buffer you want to overwrite. 

Second, could you send me the template norg file and the complete config of Neorg (for lazy.nvim) you are currently using?

I'm having hard time replicating your issue...

**Comment by pysan3** [comment]
> i hav even tried inputting the dates not from the filename and get a different error:

You should pass a LuaSnip node instead of a raw string on the right hand side.
In this case, a _`text_node`_ would be useful.

An example would be something like this.

```lua
local ls = require("luasnip")
local t = ls.text_node

-- ...

M.keywords = {
  TITLE_YESTERDAY = t(yesterday),
  TITLE_TOMORROW = t(tomorrow),
}
```

Although this is actually already defined as predefined keywords in this plugin.
In order to use it, change all occurrence of `TITLE_YESTERDAY` in your template file to `YESTERDAY` which is defined here. (As well as `TOMORROW`)

https://github.com/pysan3/neorg-templates/blob/3af2feefa9d347cbc51001c7499faaf04f62eb76/lua/neorg/modules/external/templates/default_snippets.lua#L87-L88

**Comment by pysan3** [comment]
Hey @snelling-a , did you manage to fix it?

**Comment by snelling-a** [comment]
I did not. Feel free to close the issue. I’ve put migrating my notes to Neorg on ice for now

**Comment by pysan3** [comment]
> I’ve put migrating my notes to Neorg on ice for now

Sad to hear that but I got it.

If you come back to this issue, please create a new issue since I have added issue templates so that I can help you more quickly :)

https://github.com/pysan3/neorg-templates/blob/main/.github/ISSUE_TEMPLATE/bug-report.md
